# Packages, exported artifacts, and release engineering processes.

# Special job to package regressiontest files and have them available for testing
# Runs during pre-build
# Set up to only fetch the files and prepare everything for merge requests
gromacs:prepare:
  extends:
    - .variables:default
    - .rules:always
  cache: {}
  image: biophysics/gcc-gromacs
  stage: pre-build

  variables:
    KUBERNETES_CPU_LIMIT: 1
    KUBERNETES_CPU_REQUEST: 1
    KUBERNETES_MEMORY_LIMIT: 2Gi
  # Always clone the default version for this branch, release-2020 in this case
  script:
    - export SOURCEBRANCH=release-2020
    - if [[ ! -z $GROMACSSOURCEBRANCH ]] ; then
      export SOURCEBRANCH=$GROMACSSOURCEBRANCH ;
      echo "Using $SOURCEBRANCH instead of default" ;
      fi
    - export CHECKOUTCOMMIT=FETCH_HEAD
    - if [[ ! -z $GROMACSSOURCECOMMIT ]] ; then
      export CHECKOUTCOMMIT=$GROMACSSOURCECOMMIT ;
      echo "Using $CHECKOUTCOMMIT instead of head of $SOURCEBRANCH" ;
      fi
    - if [[ ! -d gromacs ]] ; then
        mkdir gromacs ;
        cd gromacs ;
        git init ;
        cd .. ;
      fi
    - cd gromacs
    - git fetch https://gitlab.com/gromacs/gromacs.git $REGTESTBRANCH
    - git checkout -qf $CHECKOUTCOMMIT
    - git clean -ffdxq
    - git gc
    - git archive -o gmx-source.tar.gz --prefix gromacs/ -9 HEAD
    - echo "Build source for branch $SOURCEBRANCH"
    - mv gmx-source.tar.gz ..
    - cd ..
  artifacts:
    paths:
      - gmx-source.tar.gz
